# Generated by Django 3.1.7 on 2021-05-02 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('artist_id', models.CharField(max_length=22)),
                ('name', models.CharField(max_length=1000)),
                ('genre', models.CharField(max_length=1000)),
                ('artist', models.CharField(max_length=1000)),
                ('tracks', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('age', models.IntegerField()),
                ('albums', models.CharField(max_length=1000)),
                ('tracks', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('album_id', models.CharField(max_length=22)),
                ('name', models.CharField(max_length=1000)),
                ('duration', models.FloatField()),
                ('times_played', models.IntegerField()),
                ('artist', models.CharField(max_length=1000)),
                ('album', models.CharField(max_length=1000)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tarea2.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tarea2.artist'),
        ),
    ]
